// Generated by CoffeeScript 1.6.1
var boots, config_coffee, config_js, config_json, configs, fs, handler, home, name, path, tools;

fs = require("fs");

path = require("path");

tools = require("./tools");

try {
  require("coffee-script");
} catch (_error) {}

home = process.env.HOME;

config_coffee = "" + home + "/.config/rain-boots.coffee";

config_js = "" + home + "/.config/rain-boots.js";

config_json = "" + home + "/.config/rain-boots.json";

exports.configs = configs = fs.existsSync(config_coffee) ? (require(config_coffee)).configs : fs.existsSync(config_js) ? (require(config_js)).configs : fs.existsSync(config_json) ? require(config_json) : {};

exports.boots = boots = function(options) {
  var all, children, name, program;
  for (program in options) {
    all = options[program];
    for (name in all) {
      configs = all[name];
      if ((configs.inputdir != null) && (configs.children == null)) {
        children = tools.recurse(configs.inputdir);
        if (configs.fileFilter != null) {
          children = children.filter(function(filename) {
            return filename.match(configs.fileFilter);
          });
        }
        all.children = children;
      }
    }
  }
  return options;
};

boots["package"] = require("../package.json");

for (name in tools) {
  handler = tools[name];
  boots[name] = handler;
}
