// Generated by CoffeeScript 1.6.2
var erase_file, erase_path, fs, path, recurse;

path = require("path");

fs = require("fs");

exports.recurse = recurse = function(path_name) {
  var children;

  children = [];
  (fs.readdirSync(path_name)).forEach(function(child_name) {
    var child_path;

    child_path = path.join(path_name, child_name);
    if (fs.statSync(child_path).isDirectory()) {
      return (recurse(child_path)).forEach(function(a_path) {
        return children.push(a_path);
      });
    } else {
      return children.push(child_path);
    }
  });
  return children;
};

exports.write = function(filename, content) {
  return fs.writeFileSync(filename, content, "utf8");
};

exports.read = function(filename) {
  return fs.readFileSync(filename, "uf8");
};

exports.log = console.log;

exports.erase_path = erase_path = function(path_name) {
  var file_list, status;

  if (fs.existsSync(path_name)) {
    status = fs.statSync(path_name);
    if (status.isDirectory()) {
      file_list = fs.readdirSync(path_name);
      file_list.forEach(function(file_name) {
        var file_path;

        file_path = path.join(path_name, file_name);
        return erase_path(file_path);
      });
      return fs.rmdirSync(path_name);
    } else {
      return erase_file(path_name);
    }
  } else {
    return console.log("no path named", path_name);
  }
};

exports.erase_file = erase_file = function(file_name) {
  if (fs.existsSync(file_name)) {
    return fs.unlinkSync(file_name);
  } else {
    return console.log("no file named", file_name);
  }
};
