// Generated by CoffeeScript 1.6.1
var fs, path, recurse;

path = require("path");

fs = require("fs");

exports.recurse = recurse = function(path_name) {
  var children;
  children = [];
  (fs.readdirSync(path_name)).forEach(function(child_name) {
    var child_path;
    child_path = path.join(path_name, child_name);
    if (fs.statSync(child_path).isDirectory()) {
      return (recurse(child_path)).forEach(function(a_path) {
        return children.push(a_path);
      });
    } else {
      return children.push(child_path);
    }
  });
  return children;
};

exports.write = function(filename, content) {
  return fs.writeFileSync(filename, content, "utf8");
};

exports.read = function(filename) {
  return fs.readFileSync(filename, "uf8");
};

exports.log = console.log;
